Socket.io
M4TThys123/Blok-Tech-Team pull request #60
Opened 2021-03-25 15:28 UTC by ROEL2407

socket.io toegevoegd en werkend gekregen.

2021-03-25 17:46 UTC, timmit147 requested changes
Code ziet er goed uit index.html inline css alleen nog in style.css zetten.

2021-03-26 11:30 UTC, ROEL2407 commented
> Code ziet er goed uit index.html inline css alleen nog in style.css zetten.

Moest er sowieso uit bedenk ik me net, dacht dat ik dat al gedaan had

2021-03-26 11:36 UTC, marloestacx approved these changes
Ziet er goed uit

2021-03-26 11:42 UTC, timmit147 approved these changes
Ziet er goed uit.

2021-03-26 11:42 UTC, merged